services:
  app:
    container_name: xrpl-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://xrpl:xrpl@host.docker.internal:27017
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - xrpl-network

networks:
  xrpl-network:
    name: xrpl-network 