services:
  app:
    container_name: xrpl-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://xrpl:xrpl@xrpl-mongo:27017/
      - MONGO_DB_NAME=xrpl_transactions
      - DOCKER_ENV=true
    restart: unless-stopped
    networks:
      - xrpl-tag-streamer_local
    external_links:
      - xrpl-mongo

networks:
  xrpl-tag-streamer_local:
    external: true 